website/src/index.html

- removed "to" from the introduction section
- added "one" to the feature section

#10: Fixed website spelling errors

---

documentation/04_basic_features.md
jitar/src/runtime/serialization/ArrayBufferSerializer.ts
jitar/src/runtime/serialization/ValueSerializer.ts
jitar/src/runtime/serialization/types/SerializedArrayBuffer.ts
jitar/src/runtime/serialization/types/TypedArray.ts
jitar/test/_fixtures/runtime/serialization/ValueSerializer.fixture.ts
jitar/test/runtime/serialization/ValueSerializer.spec.ts

Resolves #46 
- Created the ArrayBufferSerializer
- Added tests for some of the TypedArray types
- Updated docs

Implemented the ArrayBufferSerializer

---

.github/dependabot.yml

Updated configuration to not only scan jitar, but also the other packages.
Fixes #74 
- Updated dependabot configuration to scan all npm packages we publish

Fixed configuration

---

packages/jitar-nodejs-server/package-lock.json
packages/jitar-nodejs-server/package.json
packages/jitar-nodejs-server/src/JitarServer.ts
packages/jitar-nodejs-server/src/configuration/ServerOptions.ts
packages/jitar-nodejs-server/src/controllers/AssetsController.ts
packages/jitar-nodejs-server/src/controllers/HealthController.ts
packages/jitar-nodejs-server/src/controllers/ModulesController.ts
packages/jitar-nodejs-server/src/controllers/NodesController.ts
packages/jitar-nodejs-server/src/controllers/ProceduresController.ts
packages/jitar-nodejs-server/src/controllers/ProxyController.ts
packages/jitar-nodejs-server/src/controllers/RPCController.ts
packages/jitar-nodejs-server/src/utils/LogBuilder.ts

Fixes #92
Closes #88 #87 #85 #81  
- Created log builder to build a logger for us
- Added types to the Logger as required by tslog v4
- Updated all depenencies identified by @dependabot

#92 implement tslog version 4

---

documentation/05_advanced_features.md
documentation/_data/navigation.yml
package-lock.json
packages/jitar-nodejs-server/src/controllers/RPCController.ts
packages/jitar/package.json
packages/jitar/src/lib.ts
packages/jitar/src/runtime/ProcedureRunner.ts
packages/jitar/src/runtime/middleware/CorsMiddleware.ts

Fixes #130 
- Implemented the CORS middleware
- Updated the documentation

Implemented CORS middleware

---

documentation/05_advanced_features.md
packages/jitar/src/runtime/middleware/CorsMiddleware.ts

Fixes #132 
- Support for setting the allowed headers in a CORS request

132 option to set the allowed cors headers

---

documentation/04_basic_features.md

Fixes #141 
- Added more descriptive text about unsegmented procedures

docs: updated description of unsegmented procedures

---

packages/jitar-reflection/src/models/ReflectionAlias.ts
packages/jitar-reflection/src/models/ReflectionClass.ts
packages/jitar-reflection/src/models/ReflectionExport.ts
packages/jitar-reflection/src/models/ReflectionField.ts
packages/jitar-reflection/src/models/ReflectionFunction.ts
packages/jitar-reflection/src/models/ReflectionGenerator.ts
packages/jitar-reflection/src/models/ReflectionGetter.ts
packages/jitar-reflection/src/models/ReflectionImport.ts
packages/jitar-reflection/src/models/ReflectionScope.ts
packages/jitar-reflection/src/models/ReflectionSetter.ts
packages/jitar-reflection/src/models/ReflectionValue.ts
packages/jitar-reflection/src/parser/Lexer.ts
packages/jitar-reflection/src/parser/Parser.ts
packages/jitar-reflection/test/_fixtures/parser/Lexer.fixture.ts
packages/jitar-reflection/test/_fixtures/parser/Parser.fixture.ts
packages/jitar-reflection/test/parser/Lexer.spec.ts
packages/jitar-reflection/test/parser/Parser.spec.ts

Fixes #179 
- added support for destructuring arrays and objects
- added support for character escaping in strings
- improved support for minified code (no space between keyword and literal)

fix(reflection): added missing parsing options

---

package-lock.json
packages/jitar-reflection/src/Reflector.ts
packages/jitar-reflection/src/parser/Parser.ts
packages/jitar-reflection/test/parser/Parser.spec.ts
packages/jitar/src/runtime/caching/ImportRewriter.ts
packages/jitar/test/_fixtures/runtime/caching/ImportRewriter.fixture.ts

Fixes #181 
- Exposed parsing imports and exports in the reflector
- Preserved the * as import name when importing all module members
- Added support for importing module members (actual fix)

fix(caching): import commonjs modules

---

packages/jitar/src/runtime/caching/ImportRewriter.ts
packages/jitar/test/_fixtures/runtime/caching/ImportRewriter.fixture.ts

Fixes #194 
- Always use the name specified for default imports

fix(caching): undefined commonJS import

---

packages/jitar-reflection/src/parser/Parser.ts
packages/jitar-reflection/test/_fixtures/parser/Parser.fixture.ts
packages/jitar-reflection/test/parser/Parser.spec.ts

Fixes #198
- Added support for dynamic imports

feat(reflection): dynamic import support

---

packages/jitar-reflection/README.md
packages/jitar-reflection/src/Reflector.ts
packages/jitar-reflection/src/lib.ts
packages/jitar-reflection/src/models/ReflectionClass.ts
packages/jitar-reflection/src/models/ReflectionDeclaration.ts
packages/jitar-reflection/src/models/ReflectionDestructuredArray.ts
packages/jitar-reflection/src/models/ReflectionDestructuredObject.ts
packages/jitar-reflection/src/models/ReflectionDestructuredValue.ts
packages/jitar-reflection/src/models/ReflectionField.ts
packages/jitar-reflection/src/models/ReflectionIdentifier.ts
packages/jitar-reflection/src/models/ReflectionModule.ts
packages/jitar-reflection/src/models/ReflectionParameter.ts
packages/jitar-reflection/src/models/ReflectionScope.ts
packages/jitar-reflection/src/parser/Parser.ts
packages/jitar-reflection/test/Reflector.spec.ts
packages/jitar-reflection/test/_fixtures/models/ReflectionClass.fixture.ts
packages/jitar-reflection/test/_fixtures/models/ReflectionModule.fixture.ts
packages/jitar-reflection/test/_fixtures/models/ReflectionScope.fixture.ts
packages/jitar-reflection/test/_fixtures/parser/Parser.fixture.ts
packages/jitar-reflection/test/models/ReflectionClass.spec.ts
packages/jitar-reflection/test/models/ReflectionModule.spec.ts
packages/jitar-reflection/test/models/ReflectionScope.spec.ts
packages/jitar-reflection/test/parser/Parser.spec.ts
packages/jitar/src/runtime/utils/ModuleAnalyser.ts
packages/jitar/test/runtime/utils/ModuleAnalyser.spec.ts

Fixes #210 
- Added `ReflectionDeclaration` model that supports destructured identifiers
- Added `ReflectionDestructedArray` model
- Added `ReflectionDestructedObject` model

feat(reflection): destructuring support

---

documentation/01_introduction.md
documentation/02_getting_started.md
documentation/03_runtime_services.md
documentation/04_basic_features.md
documentation/05_advanced_features.md
documentation/06_building_applications.md
documentation/07_deployment.md
examples/1-basic/1-hello-world/package.json
examples/1-basic/2-segmentation/package.json
examples/1-basic/3-load-balancing/package.json
examples/1-basic/4-access-protection/package.json
examples/1-basic/5-multi-version/package.json
examples/1-basic/6-data-transportation/package.json
examples/1-basic/7-error-handling/package.json
examples/1-basic/8-javascript/package.json
examples/2-advanced/1-start-hooks/package.json
examples/2-advanced/2-run-procedure/package.json
examples/2-advanced/3-health-checks/package.json
examples/2-advanced/4-middleware/package.json
examples/3-apps/1-full-stack/package.json
examples/3-apps/2-microservices/package.json
packages/create-jitar/templates/jitar-only/package.json
packages/create-jitar/templates/lit/package.json
packages/create-jitar/templates/react/package.json
packages/create-jitar/templates/solid/package.json
packages/create-jitar/templates/svelte/package.json
packages/create-jitar/templates/vue/package.json

Fixes #214 
- Removed documentation references to --experimental-fetch flag
- Fixed dead links in the documentation
- Removed --experimental-flag from starter scripts

chore: removed references to experimental-fetch

---

packages/serialization/src/SerializerBuilder.ts
packages/serialization/src/serializers/UrlSerializer.ts
packages/serialization/src/serializers/errors/InvalidDateString.ts
packages/serialization/src/serializers/errors/InvalidUrlString.ts
packages/serialization/src/types/serialized/SerializedUrl.ts
packages/serialization/test/_fixtures/serializers/UrlSerializer.fixture.ts
packages/serialization/test/serializers/UrlSerializer.spec.ts

Fixes #222 
- url serialzer implemented

feat(serialization): added the url serializer

---

.github/workflows/nodejsci.yml

Fixes #266 
- Added node 20.x to ci pipeline

chore(build): add node 20 to ci pipeline

---

examples/.gitignore
packages/.gitignore
packages/create-jitar/templates/jitar-only/_gitignore
packages/create-jitar/templates/lit/_gitignore
packages/create-jitar/templates/react/_gitignore
packages/create-jitar/templates/solid/_gitignore
packages/create-jitar/templates/svelte/_gitignore
packages/create-jitar/templates/vue/_gitignore
packages/server-nodejs/src/definitions/RuntimeDefaults.ts

Fixes #279 
- Updated the default cache location to .jitar
- Updated the starters to ignore .jitar

feat(server): default cache location to .jitar folder

---

packages/server-nodejs/src/configuration/ServerOptions.ts
packages/server-nodejs/src/controllers/HealthController.ts
packages/server-nodejs/src/controllers/RPCController.ts

Fixes #292 
- Fixed loglevel configuration property
- Assured to return either a string or an object as response value

fix(server): non-string primitive type response

---

packages/runtime/src/services/ProcedureRuntime.ts
packages/runtime/test/_fixtures/interfaces/Middleware.fixture.ts
packages/runtime/test/services/ProcedureRuntime.spec.ts

Fixes #290 
- Reversed the execution order of the middleware (first added gets executed first)

feat(runtime): Reversed middleware execution order

---

package-lock.json
packages/jitar/package.json

Fixes #314 
- Moved the dependencies on our own packages to devDependencies
- Installation size reduced, as not all @jitar packages are installed

chore(packaging): @jitar deps to devDependencies

---

.eslintrc.json
packages/caching/src/building/ApplicationCacheWriter.ts
packages/caching/src/building/ApplicationReader.ts
packages/plugin-vite/src/index.ts
packages/runtime/src/services/NodeMonitor.ts
packages/runtime/test/services/LocalGateway.spec.ts
packages/runtime/test/services/LocalNode.spec.ts
packages/runtime/test/services/LocalRepository.spec.ts
packages/runtime/test/services/NodeBalancer.spec.ts
packages/serialization/src/serializers/ArraySerializer.ts
packages/serialization/src/serializers/ClassSerializer.ts
packages/serialization/src/serializers/SetSerializer.ts
packages/serialization/test/DefaultClassLoader.spec.ts
packages/serialization/test/Serializer.spec.ts
packages/serialization/test/serializers/ClassSerializer.spec.ts
packages/serialization/test/serializers/DateSerializer.spec.ts
packages/serialization/test/serializers/UrlSerializer.spec.ts
packages/server-nodejs/src/utils/LocalFileManager.ts

Fixes #282 
- updated linter config to detect return await
- removed all unnecessary await statements

chore(build): update linter to eliminate returns of await in async functions

---

examples/concepts/data-transportation/requests.http
packages/runtime/src/services/Remote.ts
packages/runtime/src/services/RemoteGateway.ts
packages/runtime/src/services/RemoteNode.ts
packages/runtime/src/services/RemoteRepository.ts
packages/server-nodejs/src/JitarServer.ts
packages/server-nodejs/src/controllers/RPCController.ts

Fixes #323 
- Removed the serialization control from the runtime (is now always on)
- Simplified the serialization control in the server (only listens to the query param)

bug(server): serialization control at the gateway

---

documentation/docs/internals/data-serialization.md
packages/server-nodejs/src/JitarServer.ts

Fixes #302
- add your own serializer
- get the jitar class loader

feat(server): add custom serializers

---

.github/workflows/nodejsci.yml

Fixes #370 
- new version of node added to ci

chore(build): add node v21 into pipeline

---

packages/reflection/src/parser/Parser.ts
packages/reflection/src/parser/definitions/Keyword.ts
packages/reflection/test/_fixtures/parser/Parser.fixture.ts
packages/reflection/test/parser/Parser.spec.ts

Fixes #427 
- Added support for non-reserved keywords as identifiers

fix(reflection): non-reserved keywords as identifiers

---

packages/runtime/src/definitions/Files.ts
packages/runtime/src/errors/FileNotFound.ts
packages/runtime/src/utils/VersionParser.ts
packages/runtime/test/utils/VersionParser.spec.ts
packages/server-nodejs/src/JitarServer.ts
packages/server-nodejs/src/controllers/AssetsController.ts
packages/server-nodejs/src/controllers/HealthController.ts
packages/server-nodejs/src/controllers/ModulesController.ts
packages/server-nodejs/src/controllers/NodesController.ts
packages/server-nodejs/src/controllers/ProceduresController.ts
packages/server-nodejs/src/controllers/RPCController.ts
packages/server-nodejs/src/definitions/ContentTypes.ts
packages/server-nodejs/src/definitions/Headers.ts
packages/server-nodejs/src/definitions/RuntimeDefaults.ts
packages/server-nodejs/src/utils/LocalFileManager.ts

Fixes #402
Closes #403
Closes #405
Closes #415
- added validations for versions, fqn, assets, segments
- added definitions for headers and content types
- added default header to prevent content sniffing
- check for path traversal in file manager

feat(server): improved server-side validations

---

README.md

Fixes #434 
- Improved the introduction text

#434: Updated readme introduction

---

packages/runtime/src/models/Request.ts
packages/runtime/src/models/Response.ts
packages/runtime/src/services/Remote.ts

Fixes #436 
- Mapped remote response headers
- Always using lower-cased headers

#436: Mapped remote response headers

---

CHANGELOG.md
lerna.json
migrations/migrate-from-0.5.x-to-0.6.x.md
package-lock.json
packages/caching/package.json
packages/create-jitar/package.json
packages/jitar/package.json
packages/plugin-vite/package.json
packages/reflection/package.json
packages/runtime/package.json
packages/serialization/package.json
packages/server-nodejs/package.json

Fixes #442 
- Release version 0.6

442 release version 06

---

examples/concepts/access-protection/requests.http
examples/concepts/access-protection/src/game/checkSecret.ts
examples/concepts/access-protection/src/game/getSecret.ts
examples/concepts/access-protection/src/web/guessSecret.ts
packages/runtime/src/services/Remote.ts
packages/runtime/test/_fixtures/services/Remote.fixture.ts
packages/runtime/test/services/NodeBalancer.spec.ts
packages/runtime/test/services/NodeMonitor.spec.ts
packages/runtime/test/services/Remote.spec.ts
packages/runtime/test/services/RemoteNode.spec.ts
packages/server-nodejs/src/controllers/RPCController.ts
packages/server-nodejs/src/definitions/ContentTypes.ts

Fixes #451
- Introduced own content-types to indicate the return type (boolean / number)
- Set the return type based on the content
- Parse return value based on content type header

fix(runtime): fixed incorrect parsing of return values

---

packages/server-nodejs/src/JitarServer.ts

Fixes #449
- added try catch statements to catch errors and properly stop the server

feat(serer): handle exceptions during start and stop

---

packages/server-nodejs/src/controllers/RPCController.ts

Fixes #465 
- Skip some headers when mapping the response header

bug(server): ignore some headers in response header mapping

---

examples/apps/contact-list/package.json
examples/concepts/access-protection/package.json
examples/concepts/construction/package.json
examples/concepts/cors/package.json
examples/concepts/data-transportation/package.json
examples/concepts/error-handling/package.json
examples/concepts/health-checks/package.json
examples/concepts/hello-world/package.json
examples/concepts/load-balancing/package.json
examples/concepts/middleware/package.json
examples/concepts/multi-version/package.json
examples/concepts/node-client/package.json
examples/concepts/overrides/package.json
examples/concepts/segmentation/package.json
package-lock.json

Fixes #467
- always use the latest version of jitar, so we can test our changes with confidence

chore(examples): always use latest version of jitar

---

changelog.hbs

Fixes #469 
- Breaking changes regex added to the handlebar template

chore: display breaking changes explicitly in changelog

---

CHANGELOG.md
lerna.json
package-lock.json
package.json
packages/caching/package.json
packages/create-jitar/package.json
packages/jitar/package.json
packages/plugin-vite/package.json
packages/reflection/package.json
packages/runtime/package.json
packages/serialization/package.json
packages/server-nodejs/package.json

472 release 07

---

packages/runtime/src/utils/Environment.ts
packages/runtime/src/utils/ModuleLoader.ts

Fixes #474 
- Added environment util that determines the runtime (server or browser)
- Loading Jitar as library when running on server
- Loading Jitar from repository when running on browser

fix(runtime): environment specific loading of Jitar

---

package-lock.json
packages/server-nodejs/package.json

Fixes #507 
- update express to fix [CVE-2024-29041](https://github.com/advisories/GHSA-rv95-896h-c2vc)

chore(deps): update express

---

packages/create-jitar/src/index.ts
packages/create-jitar/templates/lit/src/my-element.ts
packages/create-jitar/templates/solid/src/App.tsx
packages/create-jitar/templates/svelte/src/main.ts
packages/reflection/src/models/ReflectionClass.ts
packages/reflection/src/parser/Parser.ts
packages/serialization/src/serializers/ClassSerializer.ts
packages/serialization/src/serializers/ErrorSerializer.ts
packages/server-nodejs/src/configuration/StandaloneConfiguration.ts
packages/server-nodejs/src/controllers/RPCController.ts
packages/server-nodejs/src/errors/ConversionError.ts
packages/server-nodejs/src/utils/RuntimeConfigurator.ts

Fixes #525 
- removed unnecessary typing
- use `nullish coalescing`
- removed unused imports, constructor, etc.

chore: fixed sonar issues

---

packages/cli/src/commands/StartServer.ts
packages/http/src/HttpRemote.ts
packages/http/src/HttpServer.ts
packages/http/src/errors/InvalidWorkerId.ts
packages/runtime/src/server/Server.ts
packages/runtime/src/server/types/RemoveWorkerRequest.ts
packages/services/src/Remote.ts
packages/services/src/gateway/Gateway.ts
packages/services/src/gateway/LocalGateway.ts
packages/services/src/gateway/RemoteGateway.ts
packages/services/src/gateway/WorkerManager.ts
packages/services/src/gateway/errors/UnknownWorker.ts
packages/services/src/gateway/utils/IdGenerator.ts
packages/services/src/worker/LocalWorker.ts
packages/services/src/worker/RemoteWorker.ts
packages/services/src/worker/Worker.ts
packages/services/test/gateway/LocalGateway.spec.ts
packages/services/test/gateway/WorkerManager.spec.ts
packages/services/test/gateway/fixtures/localGateways.fixture.ts
packages/services/test/gateway/fixtures/remoteWorkers.fixture.ts
packages/services/test/gateway/fixtures/remotes.fixture.ts
packages/services/test/gateway/fixtures/values.fixture.ts
packages/services/test/gateway/fixtures/workerManagers.fixture.ts

Fixes #409
- prevent shutdown signal to be processed more than once
- remove worker from gateway when worker is signaled to shutdown

feat(services): deregister worker on exit

---

packages/execution/test/ExecutionManager.spec.ts
packages/serialization/test/Serializer.spec.ts
packages/serialization/test/serializers/BigIntSerializer.spec.ts
packages/serialization/test/serializers/ClassSerializer.spec.ts
packages/serialization/test/serializers/DateSerializer.spec.ts
packages/serialization/test/serializers/RegExpSerializer.spec.ts
packages/serialization/test/serializers/UrlSerializer.spec.ts
packages/serialization/test/serializers/fixtures/regularExpressions.fixture.ts
packages/services/src/gateway/errors/UnknownWorker.ts
packages/services/test/gateway/LocalGateway.spec.ts
packages/services/test/gateway/WorkerBalancer.spec.ts
packages/services/test/gateway/WorkerManager.spec.ts
packages/services/test/repository/LocalRepository.spec.ts
packages/services/test/worker/LocalWorker.spec.ts

Fixes #581
- Vitest 3 is going to change the way unhandled promises are handled, these should be awaited by us. The warning is already present in Vitest 2, so better be prepared.

chore: await uncaught promises in tests

---

packages/build/src/target/module/LocationRewriter.ts
packages/build/src/target/segment/Builder.ts

Fixes #606 
- rewrite imports without members to common imports (fixes case 1);
- filter import keys bases on the actual import / export members (fixes case 2);
- skip segmented modules without members (bonus fix).

fix: import rewrite issues

---

packages/serialization/src/SerializerBuilder.ts
packages/serialization/src/serializers/BufferSerializer.ts
packages/serialization/src/serializers/errors/InvalidBufferString.ts
packages/serialization/src/types/serialized/SerializedBuffer.ts
packages/serialization/test/serializers/BufferSerializer.spec.ts
packages/serialization/test/serializers/fixtures/buffers.fixture.ts
packages/serialization/test/serializers/fixtures/index.ts

Fixes #614 
- Buffer serializer

feat: buffer serialization

---

packages/serialization/src/SerializerBuilder.ts

Fixes #616 
- Check if `Buffer` class is available before adding its serializer

#616: adding buffer serializer if Buffer class available

---

CHANGELOG.md
lerna.json
package-lock.json
package.json
packages/create-jitar/package.json
packages/jitar/package.json
packages/plugin-vite/package.json

chore: release v0.9.1
