MaskingTechnology/jitar

examples/2-advanced/1-start-hooks/package-lock.json, examples/2-advanced/1-start-hooks/package.json, examples/2-advanced/2-run-procedure/package-lock.json, examples/2-advanced/2-run-procedure/package.json, examples/3-apps/1-full-stack/package-lock.json, examples/3-apps/1-full-stack/package.json, website/package-lock.json, website/package.json
Updated all package.json files with cpx2
=> Replaced cpx with cpx2

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Fixes #16 
- Initial template for pull requests
@petermasking
=> set up the pr template

website/src/css/layout.css, website/src/index.html
- Improved the readability of the articles (set the font-weight to light instead of extra-light)
- Now opening a new tab for all external links (including the docs)
- Improved the framework agnostic sentence
- Fixed the icon of the 'source code' button
=> #25: processed feedback.

jitar/src/runtime/ClientId.ts, jitar/src/runtime/LocalRepository.ts, jitar/src/server/controllers/ModulesController.ts, jitar/test/runtime/ClientId.spec.ts, jitar/test/runtime/LocalRepository.spec.ts
- added ClientId class to centralize client id logic
- added client id type and content validation to the module controller
=> #21: improved the client id generation and validation

documentation/_includes/header.html, documentation/_layouts/default.html, documentation/assets/css/site.css, documentation/assets/libs/responsive.js
- code scrolling when overflowing on small screens
- responsiveness for mobile views
- improved font-weight usage
- improved active page subject indicator
=> 5 make docs mobile friendly

CHANGELOG.md, jitar/package.json
- updated package version to 0.1.1
- more project info to the package
- changelog with v0.1.1
=> Added v0.1.1 information

examples/1-basic/1-hello-world/package-lock.json, examples/1-basic/1-hello-world/package.json, examples/1-basic/2-segmentation/package-lock.json, examples/1-basic/2-segmentation/package.json, examples/1-basic/3-load-balancing/package-lock.json, examples/1-basic/3-load-balancing/package.json, examples/1-basic/4-access-protection/package-lock.json, examples/1-basic/4-access-protection/package.json, examples/1-basic/5-multi-version/package-lock.json, examples/1-basic/5-multi-version/package.json, examples/1-basic/6-data-transportation/package-lock.json, examples/1-basic/6-data-transportation/package.json, examples/1-basic/7-error-handling/package-lock.json, examples/1-basic/7-error-handling/package.json, examples/1-basic/8-javascript/package-lock.json, examples/1-basic/8-javascript/package.json, examples/2-advanced/1-start-hooks/package-lock.json, examples/2-advanced/1-start-hooks/package.json, examples/2-advanced/2-run-procedure/package-lock.json, examples/2-advanced/2-run-procedure/package.json, examples/2-advanced/3-health-checks/package-lock.json, examples/2-advanced/3-health-checks/package.json, examples/3-apps/1-full-stack/package-lock.json, examples/3-apps/1-full-stack/package.json, examples/3-apps/1-full-stack/segments/server.segment.json, examples/3-apps/2-microservices/package-lock.json, examples/3-apps/2-microservices/package.json, examples/npm-init.sh, jitar/.npmignore, jitar/package-lock.json
Fixes #30 
- Created shell script to install and build all examples
- Updated all examples to the latest jitar version
- Included .npmignore for removing files when publishing on npm
- Fixed issues we found during testing
=> 30 publish v011

jitar/package-lock.json
Resolves #32, #33, #34, #35, #36
- Merges all the dependency updates from the dependabot
- Reviewed and tested the project with updated dependencies
=> Merge dependencies

jitar/package-lock.json, jitar/package.json
Resolves #40
Resolves #39 
Resolves #38 
- merged the dependabot updates
- added minimum version of node to package.json
=> 40 bump dependencies

examples/1-basic/8-javascript/package.json, examples/2-advanced/1-start-hooks/jitar.json, examples/3-apps/1-full-stack/conf/dev.json, examples/3-apps/1-full-stack/conf/repo.json, jitar/src/runtime/LocalRepository.ts, jitar/src/server/configuration/RepositoryConfiguration.ts, jitar/src/server/configuration/StandaloneConfiguration.ts, jitar/src/server/utils/LocalFileManager.ts, jitar/src/server/utils/RuntimeConfigurator.ts, jitar/test/_fixtures/runtime/LocalRepository.fixture.ts, jitar/test/runtime/LocalRepository.spec.ts
Closes #47 
- added allow list to the local repository
- added configuration for assets for repository and standalone mode
- updated examples with asset list
- added tests for public and private assets
@petermasking for review
=> Added asset protection

jitar/src/server/controllers/RPCController.ts
Fixes #51 
- Added all core errors to translate to 400 / 404
=> Extended error handling status codes

documentation/05_advanced_features.md
Fixes #45 
- correction of the startClient segment in the documentation
=> #45 Fixed segment in startClient documentation

documentation/04_basic_features.md, jitar/src/runtime/serialization/DateSerializer.ts, jitar/src/runtime/serialization/ValueSerializer.ts, jitar/src/runtime/serialization/types/SerializedDate.ts, jitar/test/_fixtures/runtime/serialization/ValueSerializer.fixture.ts, jitar/test/runtime/serialization/ValueSerializer.spec.ts
Closes #57 
- Implemented the date serializer
- Added tests
- Updated documentation
=> #57 Added the date serializer

examples/1-basic/1-hello-world/tsconfig.json, examples/1-basic/2-segmentation/tsconfig.json, examples/1-basic/3-load-balancing/tsconfig.json, examples/1-basic/4-access-protection/tsconfig.json, examples/1-basic/5-multi-version/tsconfig.json, examples/1-basic/6-data-transportation/tsconfig.json, examples/1-basic/7-error-handling/tsconfig.json, examples/2-advanced/1-start-hooks/tsconfig.json, examples/2-advanced/2-run-procedure/tsconfig.json, examples/2-advanced/3-health-checks/tsconfig.json, examples/3-apps/1-full-stack/src/app/common/database/getCollection.ts, examples/3-apps/2-microservices/tsconfig.json, packages/jitar-nodejs-server/package-lock.json
Fixes #67 
- Updated tsconfig with library skip
- Updated full stack example with new stricter strict from TypeScript
@petermasking
=> Updated examples to also support TypeScript 4.8

packages/jitar-vite-plugin/package-lock.json, packages/jitar-vite-plugin/package.json
Fixes #76 
Closes #94 #77 
- Bumped dependencies
=> Bumped dependencies

packages/jitar-nodejs-server/CHANGELOG.md, packages/jitar-nodejs-server/package.json, packages/jitar-vite-plugin/CHANGELOG.md, packages/jitar/CHANGELOG.md
Fixes #96 
- Updated change logs
=> Updated change logs

packages/jitar-nodejs-server/CHANGELOG.md
Fixes #100 
- Added fix in 0.2.3
=> Updated changelog

examples/1-basic/1-hello-world/package.json, examples/1-basic/2-segmentation/package.json, examples/1-basic/3-load-balancing/package.json, examples/1-basic/4-access-protection/package.json, examples/1-basic/5-multi-version/package.json, examples/1-basic/6-data-transportation/package.json, examples/1-basic/7-error-handling/package.json, examples/1-basic/8-javascript/package.json, examples/2-advanced/1-start-hooks/package.json, examples/2-advanced/2-run-procedure/package.json, examples/2-advanced/3-health-checks/package.json, examples/3-apps/1-full-stack/package.json, examples/3-apps/2-microservices/package.json, packages/jitar-nodejs-server/package-lock.json, packages/jitar-nodejs-server/package.json, packages/jitar-vite-plugin/package-lock.json, packages/jitar/package-lock.json, packages/jitar/package.json
Merged and tested all dependabot package updates
=> Dependencies 202301

documentation/04_basic_features.md, packages/jitar-nodejs-server/src/controllers/RPCController.ts, packages/jitar/src/core/errors/BadRequest.ts, packages/jitar/src/core/errors/Forbidden.ts, packages/jitar/src/core/errors/ImplementationNotFound.ts, packages/jitar/src/core/errors/InvalidRequest.ts, packages/jitar/src/core/errors/InvalidVersionNumber.ts, packages/jitar/src/core/errors/MissingParameterValue.ts, packages/jitar/src/core/errors/NotFound.ts, packages/jitar/src/core/errors/NotImplemented.ts, packages/jitar/src/core/errors/PaymentRequired.ts, packages/jitar/src/core/errors/ProcedureNotFound.ts, packages/jitar/src/core/errors/Teapot.ts, packages/jitar/src/core/errors/Unauthorized.ts, packages/jitar/src/core/errors/UnknownParameter.ts, packages/jitar/src/lib.ts, packages/jitar/src/runtime/serialization/errors/InvalidPropertyType.ts
Fixes #116 
- added generic errors
- refactored existing error to a generic type
- translated generic error to their status code
=> 116 extends exceptions to status codes mappings

README.md
Fixes #136 
- Added a link to our articles
- Added benefits and when to use jitar
=> docs(readme): added articles and benefits

README.md, examples/README.md
Fixes #
- Added integration examples to examples readme
- Added integration examples to main readme
=>  chore(docs): updated readme

examples/4-integrations/1-react/package.json, examples/4-integrations/2-vue/package.json, package-lock.json, packages/jitar-vite-plugin/package.json, packages/jitar-vite-plugin/src/index.ts
Fixes #157 
- Refactored the Vite plugin to use the advanced reflection library
=> feat(plugin): Enhance the vite plugin

examples/1-basic/1-hello-world/package.json, examples/1-basic/2-segmentation/package.json, examples/1-basic/3-load-balancing/package.json, examples/1-basic/4-access-protection/package.json, examples/1-basic/5-multi-version/package.json, examples/1-basic/6-data-transportation/package.json, examples/1-basic/7-error-handling/package.json, examples/1-basic/8-javascript/package.json, examples/2-advanced/1-start-hooks/package.json, examples/2-advanced/2-run-procedure/package.json, examples/2-advanced/3-health-checks/package.json, examples/2-advanced/4-middleware/package.json, examples/3-apps/1-full-stack/package.json, package-lock.json, packages/jitar-nodejs-server/CHANGELOG.md, packages/jitar-nodejs-server/package.json, packages/jitar-reflection/CHANGELOG.md, packages/jitar-reflection/package.json, packages/jitar-vite-plugin/CHANGELOG.md, packages/jitar-vite-plugin/package.json, packages/jitar/CHANGELOG.md, packages/jitar/src/runtime/utils/ModuleAnalyser.ts, packages/jitar/test/_fixtures/runtime/caching/RemoteBuilder.fixture.ts
Fixes #170 
- updated versions
- updated change logs
=> chore(release): version 0.3.4

.github/dependabot.yml, package-lock.json, package.json, packages/jitar-nodejs-server/package.json, packages/jitar-reflection/package.json, packages/jitar-vite-plugin/package.json, packages/jitar/package.json
Fixes #172
- updated dependabot config
- removed dev dependencies from individual packages
- added all dev dependencies to root package.json
=> chore(deps): Cleaned dev dependencies from packages

package-lock.json, packages/jitar-nodejs-server/package.json
Fixes #184 #185 #186 #187 #188
- Glob update
- Vitest update
- TypeScript ESLint update
=> chore(deps): dependabot updates

packages/jitar-reflection/src/parser/Lexer.ts, packages/jitar-reflection/src/parser/Parser.ts, packages/jitar-reflection/src/parser/definitions/Keyword.ts, packages/jitar-reflection/src/parser/definitions/TokenType.ts, packages/jitar-reflection/test/_fixtures/parser/Lexer.fixture.ts, packages/jitar-reflection/test/_fixtures/parser/Parser.fixture.ts, packages/jitar-reflection/test/parser/Lexer.spec.ts, packages/jitar-reflection/test/parser/Parser.spec.ts
Fixes #183 
- Implementation of regex parsing
=> fix(reflection): Regex with quotes

packages/jitar-nodejs-server/CHANGELOG.md, packages/jitar-nodejs-server/package.json, packages/jitar-reflection/CHANGELOG.md, packages/jitar-reflection/package.json, packages/jitar-vite-plugin/CHANGELOG.md, packages/jitar-vite-plugin/package.json, packages/jitar/CHANGELOG.md, packages/jitar/package.json
Fixes #191 
- Bumped package versions
- Updated change logs
=> chore(release): version 037

documentation/05_advanced_features.md, packages/jitar-nodejs-server/src/controllers/RPCController.ts, packages/jitar/src/runtime/ProcedureRuntime.ts, packages/jitar/src/runtime/middleware/CorsMiddleware.ts
Fixes #203 
- Quick implementation of preflight support
- Updated the docs
=> feat(server): preflight requests

.github/workflows/nodejsci.yml, packages/runtime/src/services/Remote.ts
Fixes #240 
- Updated package names for lerna
- Updated file to trigger the ci actions
=> chore(build): fix ci configuration(#240)

packages/runtime/src/errors/ModuleNotAccessible.ts, packages/runtime/src/utils/ModuleLoader.ts, packages/runtime/src/utils/UrlRewriter.ts, packages/runtime/test/_fixtures/utils/ModuleLoader.fixture.ts, packages/runtime/test/utils/ModuleLoader.spec.ts, packages/server-nodejs/src/controllers/RPCController.ts
Fixes #242
- Check if the URL stays within the base URL (project folder)
=> bug(security): secure module loading

ROADMAP.md
Fixes #236
- Removed items that are done
- Added links to the Github issues for version 1.0
- Moved response caching to beyond 1.0
=> chore: roadmap update (#236)

packages/caching/src/building/utils/RemoteBuilder.ts, packages/caching/test/_fixtures/CacheFiles.fixture.ts, packages/runtime/src/errors/ProcedureNotAccessible.ts, packages/runtime/src/globals.ts
Fixes #140 
- Generate a remote function that throws an error for private functions
=> bug: type error at private functions

packages/create-jitar/templates/jitar-only/segments/hello.segment.json, packages/create-jitar/templates/jitar-only/segments/hi.segment.json, packages/create-jitar/templates/jitar-only/src/greetings/sayBoth.ts, packages/create-jitar/templates/lit/segments/server.segment.json, packages/create-jitar/templates/react/segments/server.segment.json, packages/create-jitar/templates/react/src/App.tsx, packages/create-jitar/templates/solid/segments/server.segment.json, packages/create-jitar/templates/svelte/segments/server.segment.json, packages/create-jitar/templates/vue/segments/server.segment.json
Fixes #164 
- Added the use of hooks to the react template
- Removed the optional .js extensions from all templates
=> chore(templates): use react hooks

examples/2-advanced/2-run-procedure/src/greetings/sayBoth.ts, packages/runtime/src/globals.ts
Fixes #234 
- Added global runtime types
- Removed ts-ignores at the run-procedure example
=> #234: Added global runtime types

examples/2-advanced/1-start-hooks/src/client.ts, examples/2-advanced/1-start-hooks/src/index.html, packages/jitar/rollup.definitions.js, packages/plugin-vite/src/index.ts, packages/runtime/src/hooks/dependencies.ts, packages/runtime/src/utils/ModuleLoader.ts
Fixes #233 
- removed the usage of import maps
=> feat(runtime): removed usage of import maps

examples/2-advanced/1-start-hooks/src/client.ts, packages/plugin-vite/src/index.ts, packages/runtime/src/client.ts
Fixes #264 
- added support for node clients
=> feat(runtime): support node clients

package-lock.json, package.json, packages/server-nodejs/package.json
Fixes #267 
- Bumped dependencies for main package
- Bumped dependencies for server-nodejs
=> chore(deps): Bumped dependencies

examples/apps/contact-list/services/repository.json, examples/apps/contact-list/services/standalone.json, examples/concepts/access-protection/services/standalone.json, examples/concepts/cors/services/standalone.json, examples/concepts/data-transportation/services/repository.json, examples/concepts/data-transportation/services/standalone.json, examples/concepts/error-handling/services/repository.json, examples/concepts/error-handling/services/standalone.json, examples/concepts/health-checks/services/standalone.json, examples/concepts/hello-world/services/standalone.json, examples/concepts/load-balancing/services/repository.json, examples/concepts/load-balancing/services/standalone.json, examples/concepts/middleware/services/standalone.json, examples/concepts/multi-version/services/standalone.json, examples/concepts/node-client/services/standalone.json, examples/concepts/segmentation/services/repository.json, examples/concepts/segmentation/services/standalone.json, packages/create-jitar/templates/jitar-only/services/repository.json, packages/create-jitar/templates/jitar-only/services/standalone.json, packages/create-jitar/templates/lit/services/standalone.json, packages/create-jitar/templates/react/services/standalone.json, packages/create-jitar/templates/solid/services/standalone.json, packages/create-jitar/templates/svelte/services/standalone.json, packages/create-jitar/templates/vue/services/standalone.json, packages/server-nodejs/src/definitions/RuntimeDefaults.ts
Fixes #295
- Changed the default source location
- Updatd all service configuration to match the new defaults
=> feat(server): change default source location

packages/serialization/src/SerializerBuilder.ts, packages/serialization/src/serializers/BigIntSerializer.ts, packages/serialization/src/serializers/errors/InvalidBigIntString.ts, packages/serialization/src/types/serialized/SerializedBigInt.ts, packages/serialization/test/_fixtures/serializers/BigIntSerializer.fixture.ts, packages/serialization/test/_fixtures/serializers/RegExpSerializer.fixture.ts, packages/serialization/test/_fixtures/serializers/UrlSerializer.fixture.ts, packages/serialization/test/serializers/BigIntSerializer.spec.ts, packages/serialization/test/serializers/RegExpSerializer.spec.ts, packages/serialization/test/serializers/UrlSerializer.spec.ts
Fixes #301 
- Added support for BigInt
- Aligned the code for tests
=> feat(serialization): added bigint support

packages/runtime/src/services/Proxy.ts
- fixes working with middleware in standalone mode
Fixes #341 
- Removed the duplicate registration of the procedure runner in the Proxy
=> bug(runtime): middleware not executes properly

package-lock.json, package.json
Fixes #349 
- Updated all dependencies suggested by dependabot
=> chore(dependencies): updates

documentation/docs/guides/add-jitar-to-an-existing-project.md, examples/apps/contact-list/package.json, package-lock.json, package.json, packages/caching/vite.config.ts, packages/jitar/vite.config.ts, packages/reflection/vite.config.ts, packages/runtime/vite.config.ts
=> chore(deps): updates september

package-lock.json
=> chore(deps): october updates

CHANGELOG.md, lerna.json, package-lock.json, packages/caching/package.json, packages/create-jitar/package-lock.json, packages/create-jitar/package.json, packages/jitar/package.json, packages/plugin-vite/package.json, packages/reflection/package.json, packages/runtime/package.json, packages/serialization/package.json, packages/server-nodejs/package.json
=> chore(release): added release notes

.github/workflows/nodejsci.yml, documentation/package-lock.json, documentation/package.json, examples/apps/contact-list/package.json, package-lock.json, website/package-lock.json, website/package.json
Closes #372 
Closes #373
Closes #374 
Closes #375 
Closes #376 
Closes #377
- Updated main dependencies
- Updated docs dependences
- Updated website dependencies
=> Chore(deps): november update

changelog.hbs, package-lock.json, package.json
Fixes #303 
- added auto-changelog library for generating the changelog
- added custom template
=> chore(release): configured auto changelog

documentation/package-lock.json, package-lock.json
Closes #384 
Closes #385 
Closes #386 
Closes #392 
- npm update
=> chore(deps): additional updates december

packages/runtime/src/services/Standalone.ts
Fixes #412 
- Starting and stopping the runtime in the standalone service
=> #412: Fixed starting health checks in standalone mode

.github/workflows/codeql.yml, .gitignore, package-lock.json, package.json
Closes #417
Closes #418 
Closes #419 
Closes #420 
Closes #421 
Closes #422 
- updated github actions
- updated to lerna 8
- bumped other dependencies
=> chore(deps): january updates

.github/dependabot.yml
Fixes #424 
- Set the open pull request limit to 1
=> chore(build): updated dependabot configuration

CHANGELOG.md, lerna.json, package-lock.json, packages/caching/package.json, packages/create-jitar/package.json, packages/jitar/package.json, packages/plugin-vite/package.json, packages/reflection/package.json, packages/runtime/package.json, packages/serialization/package.json, packages/server-nodejs/package.json
=> chore(release): v0.5.1

documentation/docs/fundamentals/runtime-services.md, documentation/docs/integrate/vite-plugin.md, packages/plugin-vite/src/index.ts, packages/runtime/src/client.ts, packages/runtime/src/hooks.ts
Fixes #438 
- Added middleware support to the create client hook
- Running the handle function in the runProcedure hook
- Added middleware configuration option to the Vite plugin
=> 438 web client middleware support

examples/concepts/middleware/requests.http, examples/concepts/middleware/segments/default.segment.json, examples/concepts/middleware/services/standalone.json, examples/concepts/middleware/src/redirect.ts, examples/concepts/middleware/src/redirectMiddleware.ts, packages/runtime/src/models/Request.ts, packages/runtime/src/models/Response.ts, packages/server-nodejs/src/controllers/RPCController.ts, packages/server-nodejs/src/definitions/Headers.ts
Fixes #456 
- Setting the correct response http code depending on the result and headers
- Redirect example
=> 456 redirect from middleware

packages/runtime/src/services/Remote.ts
Fixes #479 
- Removed the expected result
- Handle all non 200 responses as errors
=> fix(runtime): calling remote void procedures

packages/caching/src/building/utils/ImportRewriter.ts, packages/caching/test/_fixtures/CacheFiles.fixture.ts, packages/caching/test/_fixtures/building/utils/ImportRewriter.fixture.ts
Fixes #483 
- Determine the import result value when building the cache
=> fix(chaching): explicit import result requests

package-lock.json
Fixes #483
- updated socks package to overcome high security issue in ip module
=> chore(deps): updated socks package

documentation/docs/fundamentals/runtime-services.md, examples/apps/contact-list/services/repository.json, examples/apps/contact-list/services/standalone.json, packages/server-nodejs/src/JitarServer.ts, packages/server-nodejs/src/configuration/RepositoryConfiguration.ts, packages/server-nodejs/src/configuration/StandaloneConfiguration.ts, packages/server-nodejs/src/controllers/AssetsController.ts, packages/server-nodejs/src/definitions/RuntimeDefaults.ts
=> feat(server): serve index on not found

CHANGELOG.md, lerna.json, package-lock.json, package.json
=> 488 release 072

CHANGELOG.md, documentation/docs/.vitepress/config.ts, documentation/docs/deploy/health-checks.md, documentation/docs/deploy/runtime-settings.md, documentation/docs/integrate/rpc-api.md, package-lock.json, package.json
Fixes #496 
- updated missing documentation
- bumped version for mono package
- generated changelog
=> chore: release version 0.7.3

lerna.json, package-lock.json, packages/jitar/package.json, packages/server-nodejs/package.json, website/src/index.html
Fixes #498 
- added twitter tag
- added og namespace
=> 498 update social information website

packages/serialization/src/serializers/ClassSerializer.ts, packages/serialization/src/types/serialized/SerializedClass.ts, packages/serialization/test/_fixtures/serializers/ClassSerializer.fixture.ts
Fixes #500
- changed constructor arguments from array to object
=> fix(serialization): improved constructor (de)serialization

packages/serialization/src/serializers/ClassSerializer.ts
Fixes #504 
- removed unnecessary type casting for variable
=> chore: processed sonar issue

examples/apps/contact-list/package.json, examples/concepts/cors/package.json, package-lock.json, package.json, packages/caching/package.json, packages/jitar/package.json, packages/runtime/package.json, packages/server-nodejs/package.json
Fixes #510 
- updated all dependencies
- corrected jitar package versioning
- updated example to accept any version for dependencies
=> chore(deps): april update

packages/create-jitar/templates/jitar-only/package.json, packages/create-jitar/templates/lit/package.json, packages/create-jitar/templates/react/package.json, packages/create-jitar/templates/solid/package.json, packages/create-jitar/templates/svelte/package.json, packages/create-jitar/templates/vue/package.json
Fixes #514 
- updated creator package to latest version
=> chore: updated jitar dependencies

examples/apps/full-stack/tsconfig.json
Fixes #521 
- excluded webui from jitar build
=> chore(examples): build webui using Vite only

.sonar-project.properties, sonar-project.properties
=> chore(build): reconfigure sonar properties

packages/runtime/src/services/LocalGateway.ts
Fixes #537 
- gateway as runtime
=> feat(runtime): gateway as runner to allow middleware

.sonar-project.properties, eslint.config.mjs, packages/analysis/src/static/Parser.ts, packages/build/src/source/segment/Reader.ts, packages/execution/src/errors/ImplementationNotFound.ts, packages/execution/src/errors/InvalidParameterValue.ts, packages/execution/src/errors/InvalidVersionNumber.ts, packages/execution/src/errors/MissingParameterValue.ts, packages/execution/src/errors/ProcedureNotFound.ts, packages/execution/src/errors/UnknownParameter.ts, packages/health/test/fixtures/healthChecks.fixture.ts, packages/http/src/HttpServer.ts, packages/middleware/test/fixtures/middlewares.fixture.ts, packages/serialization/test/fixtures/serializers.fixture.ts, packages/sourcing/src/errors/FileNotFound.ts
Fixes #557
- updated sonar cloud exclusions
- resolved last issues
=> chore(build): resolve sonar issues

documentation/package-lock.json, documentation/package.json, website/package-lock.json, website/package.json, website/src/fonts/social-icons/font.css
Fixes #578 
- updated dependencies for website and docs
- removed non compliant `speak` css property I found during testing
=> chore(deps): website and docs updated

packages/build/src/source/segment/MemberLocator.ts, packages/build/src/source/segment/Reader.ts, packages/build/src/source/segment/models/Module.ts, packages/build/src/source/segment/models/Segment.ts, packages/build/src/target/module/Builder.ts, packages/build/src/target/segment/Builder.ts
Fixes #602 
- Include trace data when locating members;
- Include re-exported modules to the segmentation;
- Distinct segmented (explicit) modules from re-exported (implicit) modules.
=> 602 implicit segmentation support

packages/cli/src/commands/StartServer.ts
Fixes #612 
- Fix for parsing the body limit value
=> fix: body limit configuration

examples/access-protection/package.json, examples/construction/package.json, examples/cors/package.json, examples/data-transportation/package.json, examples/error-handling/package.json, examples/health-checks/package.json, examples/hello-world/package.json, examples/load-balancing/package.json, examples/middleware/package.json, examples/multi-version/package.json, examples/segmentation/package.json, package-lock.json
Fixes #622
- Removed dependencies from examples for easier mantainance
=> chore: clean up example dependencies

website/package-lock.json, website/package.json
Fixes #671
- updated dependency to solve medium issue
- fixed typo (did not copy *.txt files, i.e. robot.txt)
=> chore(deps): website dependencies

eslint.config.mjs, packages/middleware/src/MiddlewareManager.ts
=> fix: middleware execution

CHANGELOG.md, packages/create-jitar/package.json, packages/jitar/package.json, packages/plugin-vite/package.json
Fixes #676
- release notes and package bumps
=> chore: release v0.10.0

README.md, ROADMAP.md
Fixes #682 
- updated readme: added article and link to quick start.
- updated roadmap: removed obsolete / finished issues.
=> chore: readme update
